name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          key: publish
      - run: cargo publish --token ${CRATES_TOKEN}